
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VentanaDatos extends javax.swing.JFrame {
    
    public MetodoNumerico nm;
    private int index;
    
    public VentanaDatos(int index) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.index = index;
        nm = new MetodoNumerico(index, this);
        lblFuncion.setText("F(x)= "+nm.f.funcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        lblFuncion = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        lblX = new javax.swing.JLabel();
        txtCifras = new javax.swing.JTextField();
        lblCifras = new javax.swing.JLabel();
        lblEs = new javax.swing.JLabel();
        lblVv = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblEjemplo = new javax.swing.JLabel();
        lblEjemplo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Iteraciones.", "Aproximacion.", "Ea", "Aceptacion.", "Es"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        lblFuncion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFuncion.setText("F(X)=");

        lblX.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblX.setText("     X =");

        lblCifras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCifras.setText("Cifras sig. =");

        lblEs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEs.setText("Es=");

        lblVv.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblVv.setText("Valor real.");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });

        lblEjemplo.setText(" ");

        lblEjemplo2.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblVv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCifras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCifras, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(lblEjemplo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 472, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEjemplo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblEs, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncion)
                    .addComponent(lblX)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEjemplo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCifras)
                    .addComponent(txtCifras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEs))
                .addGap(3, 3, 3)
                .addComponent(lblEjemplo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVv)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
    VentanaEleccion v1 = new VentanaEleccion();
    v1.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        limpiarTabla();
        if(validar()){
            return;
        }
        if(index == 14){
            nm.calcularVv14(txtCifras.getText(), txtX.getText());
        }else if(nm.calcularVv(index, Double.parseDouble(txtX.getText()))){
                    int n = Integer.parseInt(txtCifras.getText());
                    nm.calcularEs(n);
                    lblEs.setText("Es= "+nm.f.es);
        }else{
            JOptionPane.showMessageDialog(null, "Valor invalido para X");
            return;
        }
        lblVv.setText(nm.f.Vv+"");
        nm.f.iteracion = 1;
        DefaultTableModel md = (DefaultTableModel) tbDatos.getModel();
        md.addRow(new Object[]{nm.f.iteracion, nm.f.aproximacion, "", "", nm.f.es});
        while(!nm.f.aceptacion){
        nm.Fila(index);
        md.addRow(new Object[]{nm.f.iteracion, nm.f.aproximacion, nm.f.ea, nm.f.aceptacion, nm.f.es});
        }
        nm = new MetodoNumerico(index, this);
    }//GEN-LAST:event_btnCalcularMouseClicked

    public void limpiarTabla(){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tbDatos.getModel();
            int filas=tbDatos.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
        }
    }
    
    public boolean validar(){
        if(index == 14){
            if(validarEspecial()){ return true;}else{return false;}
        }
        try{
            int c = Integer.parseInt(txtCifras.getText());
            double p = Double.parseDouble(txtX.getText());
            return false;
        }catch(NumberFormatException err){
            javax.swing.JOptionPane.showMessageDialog(null,err.getMessage());
            txtX.setText("");
            txtCifras.setText("");
            return true;
        }
    }
    
    public boolean validarEspecial(){
        String []arr1 = txtCifras.getText().split(",");
        String []arr2 = txtX.getText().split(",");
        if(arr1.length != 5){
            javax.swing.JOptionPane.showMessageDialog(null,"For input: \""+txtCifras.getText()+"\"");
            txtX.setText("");
            txtCifras.setText("");
            return true;
        }
        if(arr2.length != 2){
            javax.swing.JOptionPane.showMessageDialog(null,"For input: \""+txtX.getText()+"\"");
            txtX.setText("");
            txtCifras.setText("");
            return true;
        }
        try{
            for(int i = 0; i < 5; i++){
                double p = Double.parseDouble(arr1[i]);
            }
            for(int i = 0; i < 2; i++){
                double p = Double.parseDouble(arr2[i]);
            }
            return false;
        }catch(NumberFormatException err){
            javax.swing.JOptionPane.showMessageDialog(null,err.getMessage());
            txtX.setText("");
            txtCifras.setText("");
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblCifras;
    public javax.swing.JLabel lblEjemplo;
    public javax.swing.JLabel lblEjemplo2;
    private javax.swing.JLabel lblEs;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblVv;
    public javax.swing.JLabel lblX;
    private javax.swing.JTable tbDatos;
    public javax.swing.JTextField txtCifras;
    public javax.swing.JTextField txtX;
    // End of variables declaration//GEN-END:variables
}
